--FACT_DEUDACLIENTE

DROP TABLE FACT_DEUDACLIENTE;

CREATE TABLE FACT_DEUDACLIENTE(
Codmes CHAR(6) NOT NULL, 
CodClienteSBS VARCHAR2(15) NOT NULL,
CodEntidadFinanciera CHAR(5) NOT NULL,
CodTipCreditoSBS CHAR(2) NOT NULL,
CodCuentaContable CHAR(14) NOT NULL,
CodSubproducto CHAR(2),
CondicionCliente INTEGER,
ClasificacionCliente CHAR(1),
MtoDeudaCliente NUMBER(16,4)
--CONSTRAINT PK_FactDeudaCliente PRIMARY KEY (Codmes,CodClienteSBS,CodEntidadFinanciera,CodTipCreditoSBS,CodCuentaContable)
)

SELECT * FROM FACT_DEUDACLIENTE;

TRUNCATE TABLE FACT_DEUDACLIENTE;

INSERT INTO FACT_DEUDACLIENTE(
CODMES,
CODCLIENTESBS,
CODENTIDADFINANCIERA,
CODTIPCREDITOSBS,
CODCUENTACONTABLE,
CODSUBPRODUCTO,
CONDICIONCLIENTE,
CLASIFICACIONCLIENTE,
MTODEUDACLIENTE
) 
SELECT
PERIODO,
CODCLIENTESBS,
TRIM(TO_CHAR(CODENTIDADFINANCIERA, '00000')),
TIPCREDITOSBS,
CODCUENTACONTABLE,
CASE
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS = '09' THEN 's1' --Prestamo Pequeña Empresa
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS = '10' THEN 's2' --Prestamo MicroEmpresa
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS = '13' AND
         SUBSTR(CODCUENTACONTABLE,7,2) NOT IN ('23','24', '25') THEN 's3' --Hipotecario Normal
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS = '13' AND
         SUBSTR(CODCUENTACONTABLE,7,2) IN ('23','24', '25') THEN 's4' --Hipotecario MiVivienda
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS IN ('11','12') AND
         SUBSTR(CODCUENTACONTABLE,7,2) = '06' AND
         SUBSTR(CODCUENTACONTABLE,7,4) NOT IN ('0602') THEN 's5' --Prestamo Efectivo
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS IN ('11','12') AND
         SUBSTR(CODCUENTACONTABLE,7,2) = '06' AND
         SUBSTR(CODCUENTACONTABLE,7,4) IN ('0602') THEN 's6' --Prestamo Vehicular
    WHEN SUBSTR(CODCUENTACONTABLE,4,1) IN ('1','3','4','5','6') AND
         SUBSTR(CODCUENTACONTABLE,1,2) = '14' AND
         TIPCREDITOSBS IN ('11','12') AND
         SUBSTR(CODCUENTACONTABLE,7,2) = '02' THEN 's7' --Saldo de Tarjeta de Credito
    WHEN SUBSTR(CODCUENTACONTABLE,1,2) = '81' AND
         TIPCREDITOSBS IN ('11','12') AND
         SUBSTR(CODCUENTACONTABLE,4,3) = '923' THEN 's8' --Linea de Tarjeta de Credito
ELSE 's9' --Otros
END AS CODSUBPRODUCTO,
CONDICIONCLIENTE,
CLASIFICACIONCLIENTE,
MTODEUDACLIENTE
FROM
HIST_DEUDACLIENTE;
--2,099,544

COMMIT;



