-=========================================================================
--DIM_CLASIFICACIONCLIENTE;
--=========================================================================

DROP TABLE DIM_CLASIFICACIONCLIENTE;

CREATE TABLE DIM_CLASIFICACIONCLIENTE( 
ClasificacionCliente CHAR(1) NOT NULL,
DesClasificacionCliente	VARCHAR2(50),
CONSTRAINT PK_DimClasCliente PRIMARY KEY (ClasificacionCliente)
)

SELECT * FROM DIM_CLASIFICACIONCLIENTE;

TRUNCATE TABLE DIM_CLASIFICACIONCLIENTE;
INSERT INTO DIM_CLASIFICACIONCLIENTE VALUES('0','Normal');
INSERT INTO DIM_CLASIFICACIONCLIENTE VALUES('1','Con problemas Potenciales (CPP)');
INSERT INTO DIM_CLASIFICACIONCLIENTE VALUES('2','Deficiente');
INSERT INTO DIM_CLASIFICACIONCLIENTE VALUES('3','Dudoso');
INSERT INTO DIM_CLASIFICACIONCLIENTE VALUES('4','Pérdida');

COMMIT;


