--DIM_PRODUCTO

DROP TABLE DIM_PRODUCTO;

CREATE TABLE DIM_PRODUCTO( 
CodProducto CHAR(2) NOT NULL,
DescripcionProducto VARCHAR2(30),
CONSTRAINT PK_DimProducto PRIMARY KEY (CodProducto)
)

SELECT * FROM DIM_PRODUCTO;

TRUNCATE TABLE DIM_PRODUCTO;

INSERT INTO DIM_PRODUCTO VALUES('p1', 'Prestamo Pequeña Empresa');
INSERT INTO DIM_PRODUCTO VALUES('p2', 'Prestamo MicroEmpresa');
INSERT INTO DIM_PRODUCTO VALUES('p3', 'Prestamo Hipotecario');
INSERT INTO DIM_PRODUCTO VALUES('p4', 'Prestamo de Consumo');
INSERT INTO DIM_PRODUCTO VALUES('p5', 'Tarjeta de Credito');
INSERT INTO DIM_PRODUCTO VALUES('p6', 'Otros');

COMMIT;

