--DIM_DOCUMENTOPERSONA

DROP TABLE DIM_DOCUMENTOPERSONA;

CREATE TABLE DIM_DOCUMENTOPERSONA( 
CodTipDocPersona CHAR(1) NOT NULL,
DescripcionTipDocPersona VARCHAR2(50),
CONSTRAINT PK_DimDocumentoPersona PRIMARY KEY (CodTipDocPersona)
)

SELECT * FROM DIM_DOCUMENTOPERSONA;

TRUNCATE TABLE DIM_DOCUMENTOPERSONA;

INSERT INTO DIM_DOCUMENTOPERSONA VALUES('1', 'Libreta Electoral / DNI');
INSERT INTO DIM_DOCUMENTOPERSONA VALUES('2', 'Carné de Extranjería o Carta de Identidad');
INSERT INTO DIM_DOCUMENTOPERSONA VALUES('5', 'Pasaporte');


COMMIT;