--HIST_CLIENTE

DELETE FROM TMP_CLIENTE WHERE length(trim(periodo))=7; --HAY UN ERROR EN BASE, SE DUPLICA NOMBRE DE COLUMNAS COMO VALORES

DROP TABLE HIST_CLIENTE;

CREATE TABLE HIST_CLIENTE( 
periodo CHAR(6) NOT NULL, 
CodClienteSBS VARCHAR2(15) NOT NULL,
FechaReporteSBS CHAR(8),
TipoIdEmpresa CHAR(1),
NumDocEmpresa CHAR(11),
TipoIdPersona CHAR(1),
NumDocPersona VARCHAR2(15),
TipoPersona	CHAR(1),
TipoEmpresa CHAR(1),
Can_Empresa INTEGER,
DeuCalifNormal DECIMAL(6,2),
DeuCalifCPP	DECIMAL(6,2),
DeuCalifDeficiente DECIMAL(6,2),
DeuCalifDudoso DECIMAL(6,2),
DeuCalifPerdida DECIMAL(6,2),
Raz_Soc_o_AP CHAR(100),
Ape_Materna CHAR(100),
Ape_Casada CHAR(100),
Nombre1 CHAR(100),
Nombre2 CHAR(100),
CONSTRAINT PK_Cliente PRIMARY KEY (periodo,CodClienteSBS)
)

SELECT * FROM HIST_CLIENTE;

TRUNCATE TABLE HIST_CLIENTE;

INSERT INTO HIST_CLIENTE(
PERIODO,
CODCLIENTESBS,
FECHAREPORTESBS,
TIPOIDEMPRESA,
NUMDOCEMPRESA,
TIPOIDPERSONA,
NUMDOCPERSONA,
TIPOPERSONA,
TIPOEMPRESA,
CAN_EMPRESA,
DEUCALIFNORMAL,
DEUCALIFCPP,
DEUCALIFDEFICIENTE,
DEUCALIFDUDOSO,
DEUCALIFPERDIDA,
RAZ_SOC_O_AP,
APE_MATERNA,
APE_CASADA,
NOMBRE1,
NOMBRE2
) 
SELECT
PERIODO,
COD_SBS_CLI,
FEC_REPORTE,
TIP_DOC_TRI,
RUC,
TIP_DOC_IDE,
DOC_IDENTIDAD,
TIP_PERSONA,
TIP_EMPRESA,
CAN_EMPRESA,
TO_NUMBER (REPLACE (DEU_CALIF0, '.', ',')),
TO_NUMBER (REPLACE (DEU_CALIF1, '.', ',')),
TO_NUMBER (REPLACE (DEU_CALIF2, '.', ',')),
TO_NUMBER (REPLACE (DEU_CALIF3, '.', ',')),
TO_NUMBER (REPLACE (DEU_CALIF4, '.', ',')),
RAZ_SOC_O_AP,
APE_MATERNA,
APE_CASADA,
NOMBRE1,
NOMBRE2
FROM
TMP_CLIENTE;
-- 334,776


COMMIT;

-- REVISO LA INFORMACION
SELECT * FROM HIST_CLIENTE